[book]
authors = ["Lenny Peng"]
language = "zh"
multilingual = false
src = "src"
title = "Yet another Chinese rust-lang book."

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/gnu4cn/rust-lang-zh_CN"
git-repository-icon = "fa-github"

[output.html.print]
enable = false
